# -------------------------------------------------------------------------------
# Globals parameters
# -------------------------------------------------------------------------------

# MANDATORY
NSX_IP: "10.30.20.52" 
NSX_LOGIN: 'admin'
NSX_PASSWORD: 'VMware1!vmware'

# OPTIONAL
